### PR TITLE
Validate type definition as part of CI

### PR DESCRIPTION
**Pull request by MichaelMarner**
Embarrassingly, my last PR (#216) introduced a syntax error in the type definition. This PR fixes that error and also adds `dtslint` as part of the Travis CI process, so that this won't happen again.

* Fixes the syntax error
* Modifies the `npm test` script to run `dtslint` on the type definition
* Adds tslint rules so that the existing index.d.ts passes linting
* Updates `.travis.yml` to use a newer version of Node, as required by dtslint

Here's an example build showing the original error:

https://travis-ci.org/MichaelMarner/react-native-google-analytics-bridge/builds/334576677

Sorry again for introducing the error in the first place.

### CODE REVIEW

**Comment by cbrevik** [comment]
This is awesome, thanks @MichaelMarner!

**Comment by cbrevik** [comment]
Running this locally I got the following error;
```
Test with 2.6
Test with 2.5
Test with 2.4
Error: /Users/cbrevik/Dev/IH/react-native-google-analytics-bridge/index.d.ts:52:18
ERROR: 52:18   expect  Compile error in typescript@2.4 but not in typescript@2.5.
Fix with a comment '// TypeScript Version: 2.5' just under the header.
Duplicate identifier 'GoogleAnalyticsTracker'.
ERROR: 284:18  expect  Compile error in typescript@2.4 but not in typescript@2.5.
Fix with a comment '// TypeScript Version: 2.5' just under the header.
Duplicate identifier 'GoogleAnalyticsSettings'.
ERROR: 313:18  expect  Compile error in typescript@2.4 but not in typescript@2.5.
Fix with a comment '// TypeScript Version: 2.5' just under the header.
Duplicate identifier 'GoogleTagManager'.
```

Are you getting the same @MichaelMarner?

**Comment by MichaelMarner** [comment]
Hey @cbrevik I wasn't getting that error locally and it's not happening on Travis CI, but can have a look later today if it's still an issue

**Comment by cbrevik** [comment]
Hm, well looking at https://travis-ci.org/idehub/react-native-google-analytics-bridge/builds/335030345

It did build fine, but it's not saying that it's actually testing the different versions like it does locally for me:
```
Test with 2.6
Test with 2.5
Test with 2.4
```

Is it the same for you running locally?

**Comment by cbrevik** [comment]
It's fixed now via #221 
No longer an issue, thanks 😄

**Pull request merged**
