### PR TITLE
Added ecommerce tracking

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by cbrevik** [comment]
Hi there! Thanks for the PR, I've been itching to get started on this feature. Glad to see someone beat me to it.

There are two points which I think is important when considering Ecommerce tracking;

1. It should work for both iOS/Android (relevant for any new functionality really).
2. For Android, the standard Ecommerce tracking has been [deprecated in the latest SDK](https://developers.google.com/analytics/devguides/collection/android/v4/ecommerce).

What I've been thinking of is implementing [Enhanced Ecommerce transaction tracking](https://developers.google.com/analytics/devguides/collection/ios/v3/enhanced-ecommerce#measuring-transactions) for both platforms. Then we bypass the whole deprecation business, and it's possible to build upon it with more features as far as ecommerce tracking goes.

I have not tested the differences between the standard and enhanced tracking mechanisms for Ecommerce though. Maybe you are more familiar with it than me?

**Comment by gnestor** [comment]
Nope I just started playing with ecommerce tracking today. I haven't dived into React Native for Android yet, so I don't know much about that either. Let me know how I can help!

**Comment by cbrevik** [comment]
Awesome! Well code-wise it seems really quite similar to your implementation, other than the fact that the product (equivalent to "item" in the standard tracking), and the ProductAction (equivalent to "transaction") needs to accompany an event or screenView hit. 

For that event we'd probably want to let people define their own eventCategory and eventAction (even though they will likely name it something like the example, "Ecommerce" and "Purchase").

So I envision something like this for the JS API:
`trackPurchaseEvent(product = {}, transaction = {}, eventCategory = "Ecommerce", eventAction = "Purchase")`. In other words category/action are optional params with defaults.

The product object should have the following defintion;
`{ productId, name, category, brand, variant, price, couponCode, quantity }`
The transaction object should have the following definition;
`{ transactionId, affiliation, revenue, tax, shipping, couponCode }`

By the way, in your implementation I see you have included default values in the `index.js` for the objects, this should probably be avoided since they will vary depending on the country.

If you can do the iOS implementation, I can add onto that with an Android implementation. What do you think?

**Comment by gnestor** [comment]
Sure why not? I just finished adding exception, social interaction, user ID, and iOS install tracking (you can see the branches: https://github.com/gnestor/react-native-google-analytics-bridge).

**Comment by gnestor** [comment]
Ok I pushed to https://github.com/gnestor/react-native-google-analytics-bridge/tree/feature/enhanced-ecommerce

You will need to implement Android methods for `trackException`, `trackSocialInteraction`, `setUser`, and `allowIDFA` if you want to merge this branch into master. Otherwise, you can just take the `trackPurchaseEnhanced` method.

**Comment by cbrevik** [comment]
This is great work, thanks! I'll look into it this evening.

Looks like dependencies will have to be updated for `allowIDFA`, it requires `libAdIdAccess.a`. Also it might affect lead to [app rejections in App Store](http://stackoverflow.com/questions/25025028/google-analytics-ios-sdk-3-0-8-idfa-app-store-rejection). Have you looked into this?

**Comment by cbrevik** [comment]
Thanks for the great work! Since the work has diverged so much I made a new pull request.

**Pull request closed without merging**
