### PR TITLE
add experiment support

### PR DESCRIPTION
**Pull request by evollu**
add tag manager bridge for Experiments
Followed android tutorial but can't find a way to refer defaultcontainer_binary as it lives in application level. Used -1 and it seems to be working

### CODE REVIEW

**Comment by cbrevik** [comment]
Hi @evollu and thanks for this PR! I've been traveling lately and have not had time to keep working on it.

I have a partial implementation of TagManager-support on my other machine, and I'll compare notes and get back to you on this! :)

**Comment by evollu** [comment]
:+1: cool

**Comment by cbrevik** [comment]
Hi again, sorry for being slow. I've been knocked out by the flu for half a week now.

I have started looking into this PR, and the basic implementation looks solid. There are a few details (like thread queues on the iOS-implementation).

Basically what I'm doing locally is merging our two implementations, and will have this done before the end of the week.

**Comment by evollu** [comment]
:+1: thanks

**Pull request merged**
