### PR TITLE
Ecommerce, + couple of other features

### PR DESCRIPTION
**Pull request by cbrevik**
* Added a java implementation of all the other features. 
* Removed the "legacy" purchase tracking, and left the enhanced one in place. 
    * Renamed to trackPurchaseEvent
* Fixed a few errors in the iOS code.
* Added a bit more docs on top of everything.
@gnestor

### CODE REVIEW

**Comment by cbrevik** [comment]
I will test the new features a bit more before releasing. Will probably update the example project to RN 0.18 as well.

**Comment by gnestor** [comment]
Nice work! Testing now...

**Comment by gnestor** [comment]
All new tracking works for me except `allowIDFA()`. It may be that I don't have my project set up correctly. Is it working for you?

**Comment by cbrevik** [comment]
Yes, for allowIDFA you'll need to add AdSupport.framework and libAdIdAccess.a manually. Check the installation instructions at step 7 https://github.com/idehub/react-native-google-analytics-bridge#manual-installation-ios.

**Comment by cbrevik** [comment]
The reason for me explicitly excluding those two from the default "setup" is because people who do not use that feature might be rejected from submitting to the AppStore.

**Comment by gnestor** [comment]
Gotcha. I did some reading about IDFA and the App Store review process and it appears that if you use the AdSupport framework but don't display ads, your app will probably get rejected.

**Comment by cbrevik** [comment]
Yep, exactly, and if you add libAdIdAccess.a without adding AdSupport.framework, then your app won't compile. So the lib is shipped with the npm module, but people will have to make a conscious choice to add it.

**Pull request merged**
